SUBDIRS=	include types configs drivers screens
ifeq "$(NOX)" ""
  SUBDIRS+=	xmclients
endif

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
