######################################################################
#                                                                    #
#  doc/lib/Makefile                                                  #
#      Rules for making CX doc/lib (libs' documentation) subtree     #
#                                                                    #
######################################################################

SUBDIRS=	
TOPDIR=		../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
