extern dataknob_knob_vmt_t motifknobs_button_vmt;
extern dataknob_knob_vmt_t motifknobs_arrowlt_vmt;
extern dataknob_knob_vmt_t motifknobs_arrowrt_vmt;
extern dataknob_knob_vmt_t motifknobs_arrowup_vmt;
extern dataknob_knob_vmt_t motifknobs_arrowdn_vmt;
