SUBDIRS=	drv_i

EXPORTSFILES=	
EXPORTSDIR=	include

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
