######################################################################
#                                                                    #
#  lib/datatree/Makefile                                             #
#      Rules for making Data Tree library                            #
#                                                                    #
######################################################################

ARLIBS=		libdatatree.a
include		libdatatree.a_COMPONENTS.mk

MAKEFILE_PARTS+=libdatatree.a_COMPONENTS.mk

EXPORTSFILES=	$(ARLIBS)
EXPORTSDIR=	lib

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
