MONO_C_FILES=		rrund
ARLIBS=			libremdrvlet.a libremsrv.a
include			libremdrvlet.a_COMPONENTS.mk libremsrv.a_COMPONENTS.mk

MAKEFILE_PARTS+=	libremdrvlet.a_COMPONENTS.mk libremsrv.a_COMPONENTS.mk

EXPORTSFILES=		$(ARLIBS)
EXPORTSDIR=		lib

EXPORTSFILES2=		rrund
EXPORTSDIR2=		bin

######################################################################
TOPDIR=	        ../..
include		$(TOPDIR)/TopRules.mk
######################################################################
