DRV_INTERFACES=	
GIVEN_FILES=	$(DRV_INTERFACES)

EXPORTSFILES=	$(DRV_INTERFACES)
EXPORTSDIR=	include/drv_i

######################################################################
PRJDIR=		../..
include		$(PRJDIR)/PrjRules.mk
######################################################################
