ARLIBS=			libvdev.a
libvdev.a_COMPONENTS=	vdev.o

EXPORTSFILES=		$(ARLIBS)
EXPORTSDIR=		lib

SPECIFIC_CFLAGS=	-fPIC

######################################################################
TOPDIR=	        ../..
include		$(TOPDIR)/TopRules.mk
######################################################################
