.PHONY:		firsttarget
firsttarget:	all

LIBMISC_SRCDIR=		$(TOPDIR)/lib/misc
LIBUSEFUL_SRCDIR=	$(TOPDIR)/lib/useful
LIBCXSCHEDULER_SRCDIR=	$(TOPDIR)/lib/useful
LIBREMSRV_SRCDIR=	$(TOPDIR)/lib/rem
LIBREMDRVLET_SRCDIR=	$(TOPDIR)/lib/rem
LIBPZFRAME_DRV_SRCDIR=	$(TOPDIR)/lib/pzframe
RRUND_SRCDIR=		$(TOPDIR)/lib/rem

X_LIBS_COMPONENTS=	\
			$(LIBMISC_SRCDIR)/libmisc.a_COMPONENTS.mk \
			$(LIBUSEFUL_SRCDIR)/libuseful.a_COMPONENTS.mk \
			$(LIBCXSCHEDULER_SRCDIR)/libcxscheduler.a_COMPONENTS.mk \
			$(LIBREMSRV_SRCDIR)/libremsrv.a_COMPONENTS.mk \
			$(LIBREMDRVLET_SRCDIR)/libremdrvlet.a_COMPONENTS.mk \
			$(LIBPZFRAME_DRV_SRCDIR)/libpzframe_drv.a_COMPONENTS.mk
include $(X_LIBS_COMPONENTS)
MAKEFILE_PARTS+=	$(X_LIBS_COMPONENTS)

LIBMISC_SOURCES=	$(libmisc.a_COMPONENTS:.o=.c)
$(LIBMISC_SOURCES):	%: $(LIBMISC_SRCDIR)/%
LOCAL_INTMFILES+=	libmisc.a
LOCAL_GNTDFILES+=	$(LIBMISC_SOURCES)

LIBUSEFUL_SOURCES=	$(libuseful.a_COMPONENTS:.o=.c)
$(LIBUSEFUL_SOURCES):	%: $(LIBUSEFUL_SRCDIR)/%
LOCAL_INTMFILES+=	libuseful.a
LOCAL_GNTDFILES+=	$(LIBUSEFUL_SOURCES)
#----
$(LIBUSEFUL_SOURCES:.c=.%):	SPECIFIC_INCLUDES=-I$(LIBUSEFUL_SRCDIR)

LIBCXSCHEDULER_SOURCES=	$(libcxscheduler.a_COMPONENTS:.o=.c)
$(LIBCXSCHEDULER_SOURCES):	%: $(LIBCXSCHEDULER_SRCDIR)/%
LOCAL_INTMFILES+=	libcxscheduler.a
LOCAL_GNTDFILES+=	$(LIBCXSCHEDULER_SOURCES)

LIBREMSRV_SOURCES=	$(libremsrv.a_COMPONENTS:.o=.c)
$(LIBREMSRV_SOURCES):	%: $(LIBREMSRV_SRCDIR)/%
LOCAL_INTMFILES+=	libremsrv.a
LOCAL_GNTDFILES+=	$(LIBREMSRV_SOURCES)

LIBREMDRVLET_SOURCES=	$(libremdrvlet.a_COMPONENTS:.o=.c)
$(LIBREMDRVLET_SOURCES):%: $(LIBREMDRVLET_SRCDIR)/%
LOCAL_INTMFILES+=	libremdrvlet.a
LOCAL_GNTDFILES+=	$(LIBREMDRVLET_SOURCES)

LIBPZFRAME_DRV_SOURCES=	$(libpzframe_drv.a_COMPONENTS:.o=.c)
$(LIBPZFRAME_DRV_SOURCES):%: $(LIBPZFRAME_DRV_SRCDIR)/%
LOCAL_INTMFILES+=	libpzframe_drv.a
LOCAL_GNTDFILES+=	$(LIBPZFRAME_DRV_SOURCES)

RRUND_SOURCES=		rrund.c
$(RRUND_SOURCES):	%: $(RRUND_SRCDIR)/%
LOCAL_GNTDFILES+=	$(RRUND_SOURCES)

$(LIBMISC_SOURCES) $(LIBUSEFUL_SOURCES) $(LIBCXSCHEDULER_SOURCES) \
$(LIBREMSRV_SOURCES) $(LIBREMDRVLET_SOURCES) $(LIBPZFRAME_DRV_SOURCES) \
$(RRUND_SOURCES):
			$(SCRIPTSDIR)/ln-sf_safe.sh $< $@

# --------------------------------------------------------------------

ARLIBS=		libmisc.a libuseful.a libcxscheduler.a \
		libremsrv.a libremdrvlet.a libpzframe_drv.a
MONO_C_FILES=	rrund
