######################################################################
#                                                                    #
#  doc/programs/Makefile                                             #
#      Rules for making CX doc/programs (progs documentation) subtree#
#                                                                    #
######################################################################

SUBDIRS=	
TOPDIR=		../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
