DAQMX_DRIVERS=	pxi6363_drv.so

MONO_C_FILES=	$(DAQMX_DRIVERS)

DIR_INCLUDES=	$(DAQMX_INCLUDES)

######################################################################
PRJDIR=		../..
include		DAQmxDefs.mk
SECTION=	programs/drivers/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################
