######################################################################
#                                                                    #
#  lib/Cdr/Makefile                                                  #
#      Rules for making Cx Data Representation library               #
#                                                                    #
######################################################################

ARLIBS=		libCdr.a
include		libCdr.a_COMPONENTS.mk

MAKEFILE_PARTS+=libCdr.a_COMPONENTS.mk

EXPORTSFILES=	$(ARLIBS)
EXPORTSDIR=	lib

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
