######################################################################
#                                                                    #
#  Makefile                                                          #
#      Top-level CX's Makefile                                       #
#                                                                    #
######################################################################

SUBDIRS=	scripts include lib programs doc
TOPDIR=		.
include	$(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
