SUBDIRS=	include types x-build drivers screens
ifeq "$(NOX)" ""
#  SUBDIRS+=	xmclients
  SUBDIRS+=	pzframes
endif

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
