#ifndef __MAIN_BUILTINS_H
#define __MAIN_BUILTINS_H


/* Note: *builtins.c files are generated by mkbuiltins.sh */


typedef int (*init_builtins_err_notifier_t)(int magicnumber, const char *name);

int  InitBuiltins(init_builtins_err_notifier_t err_notifier);
void TermBuiltins(void);


#endif /* __MAIN_BUILTINS_H */
