ALL_SYSDEPS=	os_linux.h os_cygwin.h os_interix.h os_openbsd.h os_darwin.h

GIVEN_FILES=	$(ALL_SYSDEPS)

EXPORTSFILES=	$(ALL_SYSDEPS)
EXPORTSDIR=	include/sysdeps

######################################################################
TOPDIR=	        ../..
include		$(TOPDIR)/TopRules.mk
######################################################################
