CLIENTS=	kozdev cac208 canadc40 candac16 cdac20 ceac124 \
		cgvi8 cpks8 ckvch curvv \
		\
		v06xx \
		g0401 g0603 \
		\
		kshd485 \
		vsdc2 \
		frolov_d16 frolov_ie4 \
		frolov_k4x1 \
		s_u0632 \
		\
		s_adc200me s_adc812me dl200me_s dl200me_f \
		weld02 senkov_ebc senkov_vip \
		tvac320 panov_ubs \
		smc8

######################################################################
PRJDIR=		..
SECTION=	programs/pults/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################
