MONO_C_FILES=	slbpm_drv.so ottcam_drv.so triadatv_um_drv.so

######################################################################
PRJDIR=		../..
SECTION=	programs/drivers/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################

ottcam_drv.so:	$(LIBPZFRAME_DRV)
