SUBDIRS=	include types #screens
ifeq "$(NOX)" ""
#  SUBDIRS+=	xmclients
#  SUBDIRS+=	pzframes
endif

# Conditionally add epics,...?
SUBDIRS+=	epics
SUBDIRS+=	tango

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
