######################################################################
#                                                                    #
#  lib/datatree/Makefile                                             #
#      Rules for making Knobs Core library                           #
#                                                                    #
######################################################################

ARLIBS=		libKnobsCore.a
libKnobsCore.a_COMPONENTS=	KnobsCore_knobset.o KnobsCore_simple.o \
				KnobsCore_misc.o KnobsCore_err.o

EXPORTSFILES=	$(ARLIBS)
EXPORTSDIR=	lib

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
