#ifndef __FROLOV_SPD_DRV_I_H
#define __FROLOV_SPD_DRV_I_H


// w5i
enum
{
    FROLOV_SPD_CHAN_NUMTURNS   = 0,
    FROLOV_SPD_CHAN_NUMBUNCHES = 1,
    FROLOV_SPD_CHAN_SAWTYPE    = 2,
    FROLOV_SPD_CHAN_OPMODE     = 3,
    FROLOV_SPD_CHAN_DOSTART    = 4,

    FROLOV_SPD_NUMCHANS        = 5
};


#endif /* __FROLOV_SPD_DRV_I_H */
