#ifndef __SENKOV_VIP_DRV_I_H
#define __SENKOV_VIP_DRV_I_H


enum
{
    SENKOV_VIP_SET_n_DAC_RESERVED0 = 0,
    SENKOV_VIP_SET_n_DAC_UOUT      = 1,
    SENKOV_VIP_SET_n_DAC_CORR      = 2,
    SENKOV_VIP_SET_n_RESERVED3     = 3,
    SENKOV_VIP_SET_n_USO_COEFF     = 4,
    SENKOV_VIP_SET_n_VIP_INVRT_FRQ = 5,
    SENKOV_VIP_SET_n_VIP_IOUT_PROT = 6,
    SENKOV_VIP_SET_n_BRKDN_COUNTER = 7,

    SENKOV_VIP_SET_n_count      // =8
};

enum
{
    SENKOV_VIP_CMD_sh_VIP_ON  = 0,
    SENKOV_VIP_CMD_sh_VIP_OFF = 1,
    SENKOV_VIP_CMD_sh_HVL_ON  = 2,
    SENKOV_VIP_CMD_sh_HVL_OFF = 3,

    SENKOV_VIP_CMD_sh_count   // = 4
};

enum
{
    SENKOV_VIP_MES_n_RESERVED0     = 0,
    SENKOV_VIP_MES_n_VIP_UOUT      = 1,
    SENKOV_VIP_MES_n_VIP_IOUT_FULL = 2,
    SENKOV_VIP_MES_n_VIP_IOUT_PREC = 3,
    SENKOV_VIP_MES_n_TRANSF_IIN    = 4,
    SENKOV_VIP_MES_n_VIP_3FURECT   = 5,
    SENKOV_VIP_MES_n_VIP_3FI       = 6,
    SENKOV_VIP_MES_n_VIP_T_TRRAD   = 7,
    SENKOV_VIP_MES_n_TANK_T        = 8,
    SENKOV_VIP_MES_n_RESERVED9     = 9,
    SENKOV_VIP_MES_n_VIP_IOUT_AUTO = 10,
    SENKOV_VIP_MES_n_VIP_IOUT_AVG  = 11,

    SENKOV_VIP_MES_n_count      // =12
};

enum
{
    SENKOV_VIP_MODE_sh_POWER_ON    = 0,
    SENKOV_VIP_MODE_sh_ACTUATOR_ON = 1,
    SENKOV_VIP_MODE_sh_VIP_ON      = 2,
    SENKOV_VIP_MODE_sh_OPERATE     = 3,
    SENKOV_VIP_MODE_sh_RESERVED4   = 4,
    SENKOV_VIP_MODE_sh_RESERVED5   = 5,
    SENKOV_VIP_MODE_sh_MANUAL      = 6,
    SENKOV_VIP_MODE_sh_VIP_BLOCKED = 7,

    SENKOV_VIP_MODE_sh_count    // = 8
};

enum
{
    SENKOV_VIP_STAT_sh_RESERVED0          = 0,
    SENKOV_VIP_STAT_sh_FEEDBACK_BREAK     = 1,
    SENKOV_VIP_STAT_sh_PHASE_BREAK        = 2,
    SENKOV_VIP_STAT_sh_VIP_IIN_GT_250A    = 3,
    SENKOV_VIP_STAT_sh_VIP_IOUT_GT_1100mA = 4,
    SENKOV_VIP_STAT_sh_VIP_UOUT_GT_70kV   = 5,
    SENKOV_VIP_STAT_sh_EXT_BLOCK1_UBS     = 6,
    SENKOV_VIP_STAT_sh_CONSTANT_BRKDN     = 7,
    SENKOV_VIP_STAT_sh_NO_WATER           = 8,
    SENKOV_VIP_STAT_sh_TANK_T_GT_60C      = 9,
    SENKOV_VIP_STAT_sh_TTEMP_GT_45C       = 10,
    SENKOV_VIP_STAT_sh_IGBT_PROTECTION    = 11,
    SENKOV_VIP_STAT_sh_EXT_BLOCK2_UBS     = 12,
    SENKOV_VIP_STAT_sh_TRANSF_IIN_GT_300A = 13,
    SENKOV_VIP_STAT_sh_RESERVED14         = 14,
    SENKOV_VIP_STAT_sh_RESERVED15         = 15,
    
    SENKOV_VIP_STAT_sh_count           // = 16
};

// w8i,w4i,r12i,r8i,r16i,r2i
enum
{
    SENKOV_VIP_CHAN_SET_base = 0,
    SENKOV_VIP_CHAN_SET_DAC_RESERVED0 = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_DAC_RESERVED0,
    SENKOV_VIP_CHAN_SET_DAC_UOUT      = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_DAC_UOUT,
    SENKOV_VIP_CHAN_SET_DAC_CORR      = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_DAC_CORR,
    SENKOV_VIP_CHAN_SET_RESERVED3     = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_RESERVED3,
    SENKOV_VIP_CHAN_SET_USO_COEFF     = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_USO_COEFF,
    SENKOV_VIP_CHAN_SET_VIP_INVRT_FRQ = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_VIP_INVRT_FRQ,
    SENKOV_VIP_CHAN_SET_VIP_IOUT_PROT = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_VIP_IOUT_PROT,
    SENKOV_VIP_CHAN_SET_BRKDN_COUNTER = SENKOV_VIP_CHAN_SET_base + SENKOV_VIP_SET_n_BRKDN_COUNTER,

    SENKOV_VIP_CHAN_CMD_base,
    SENKOV_VIP_CHAN_CMD_VIP_ON        = SENKOV_VIP_CHAN_CMD_base + SENKOV_VIP_CMD_sh_VIP_ON ,
    SENKOV_VIP_CHAN_CMD_VIP_OFF       = SENKOV_VIP_CHAN_CMD_base + SENKOV_VIP_CMD_sh_VIP_OFF,
    SENKOV_VIP_CHAN_CMD_HVL_ON        = SENKOV_VIP_CHAN_CMD_base + SENKOV_VIP_CMD_sh_HVL_ON ,
    SENKOV_VIP_CHAN_CMD_HVL_OFF       = SENKOV_VIP_CHAN_CMD_base + SENKOV_VIP_CMD_sh_HVL_OFF,

    SENKOV_VIP_CHAN_MES_base,
    SENKOV_VIP_CHAN_MES_RESERVED0     = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_RESERVED0,
    SENKOV_VIP_CHAN_MES_VIP_UOUT      = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_UOUT,
    SENKOV_VIP_CHAN_MES_VIP_IOUT_FULL = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_IOUT_FULL,
    SENKOV_VIP_CHAN_MES_VIP_IOUT_PREC = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_IOUT_PREC,
    SENKOV_VIP_CHAN_MES_TRANSF_IIN    = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_TRANSF_IIN,
    SENKOV_VIP_CHAN_MES_VIP_3FURECT   = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_3FURECT,
    SENKOV_VIP_CHAN_MES_VIP_3FI       = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_3FI,
    SENKOV_VIP_CHAN_MES_VIP_T_TRRAD   = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_T_TRRAD,
    SENKOV_VIP_CHAN_MES_TANK_T        = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_TANK_T,
    SENKOV_VIP_CHAN_MES_RESERVED9     = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_RESERVED9,
    SENKOV_VIP_CHAN_MES_VIP_IOUT_AUTO = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_IOUT_AUTO,
    SENKOV_VIP_CHAN_MES_VIP_IOUT_AVG  = SENKOV_VIP_CHAN_MES_base + SENKOV_VIP_MES_n_VIP_IOUT_AVG,
    
    SENKOV_VIP_CHAN_MODE_base,
    SENKOV_VIP_CHAN_MODE_POWER_ON     = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_POWER_ON,
    SENKOV_VIP_CHAN_MODE_ACTUATOR_ON  = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_ACTUATOR_ON,
    SENKOV_VIP_CHAN_MODE_VIP_ON       = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_VIP_ON,
    SENKOV_VIP_CHAN_MODE_OPERATE      = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_OPERATE,
    SENKOV_VIP_CHAN_MODE_RESERVED4    = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_RESERVED4,
    SENKOV_VIP_CHAN_MODE_RESERVED5    = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_RESERVED5,
    SENKOV_VIP_CHAN_MODE_MANUAL       = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_MANUAL,
    SENKOV_VIP_CHAN_MODE_VIP_BLOCKED  = SENKOV_VIP_CHAN_MODE_base + SENKOV_VIP_MODE_sh_VIP_BLOCKED,

    SENKOV_VIP_CHAN_STAT_base,
    SENKOV_VIP_CHAN_STAT_RESERVED0          = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_RESERVED0,
    SENKOV_VIP_CHAN_STAT_FEEDBACK_BREAK     = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_FEEDBACK_BREAK,
    SENKOV_VIP_CHAN_STAT_PHASE_BREAK        = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_PHASE_BREAK,
    SENKOV_VIP_CHAN_STAT_VIP_IIN_GT_250A    = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_VIP_IIN_GT_250A,
    SENKOV_VIP_CHAN_STAT_VIP_IOUT_GT_1100mA = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_VIP_IOUT_GT_1100mA,
    SENKOV_VIP_CHAN_STAT_VIP_UOUT_GT_70kV   = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_VIP_UOUT_GT_70kV,
    SENKOV_VIP_CHAN_STAT_EXT_BLOCK1_UBS     = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_EXT_BLOCK1_UBS,
    SENKOV_VIP_CHAN_STAT_CONSTANT_BRKDN     = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_CONSTANT_BRKDN,
    SENKOV_VIP_CHAN_STAT_NO_WATER           = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_NO_WATER,
    SENKOV_VIP_CHAN_STAT_TANK_T_GT_60C      = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_TANK_T_GT_60C,
    SENKOV_VIP_CHAN_STAT_TTEMP_GT_45C       = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_TTEMP_GT_45C,
    SENKOV_VIP_CHAN_STAT_IGBT_PROTECTION    = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_IGBT_PROTECTION,
    SENKOV_VIP_CHAN_STAT_EXT_BLOCK2_UBS     = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_EXT_BLOCK2_UBS,
    SENKOV_VIP_CHAN_STAT_TRANSF_IIN_GT_300A = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_TRANSF_IIN_GT_300A,
    SENKOV_VIP_CHAN_STAT_RESERVED14         = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_RESERVED14,
    SENKOV_VIP_CHAN_STAT_RESERVED15         = SENKOV_VIP_CHAN_STAT_base + SENKOV_VIP_STAT_sh_RESERVED15,

    SENKOV_VIP_CHAN_CUR_BRKDN_COUNTER,
    SENKOV_VIP_CHAN_EXTRA_RESERVED,
    
    SENKOV_VIP_NUMCHANS                  // = 50
};


#endif /* __SENKOV_VIP_DRV_I_H */
