#ifndef __SENKOV_EBC_DRV_I_H
#define __SENKOV_EBC_DRV_I_H


#include "drv_i/cankoz_common_drv_i.h"


// r5i,w5i,w8i,r16i,w1i,r2i,w13i
enum
{
    SENKOV_EBC_CHAN_ADC_n_base = 0, SENKOV_EBC_CHAN_ADC_n_count = 5,
    SENKOV_EBC_CHAN_DAC_n_base = 5, SENKOV_EBC_CHAN_DAC_n_count = 5,

    /* 10-59: regs */
    SENKOV_EBC_CHAN_REGS_base  = 10,
    SENKOV_EBC_CHAN_REGS_OUTRB_n_base = SENKOV_EBC_CHAN_REGS_base + CANKOZ_IOREGS_OFS_OUTRB0,
    SENKOV_EBC_CHAN_REGS_INPRB_n_base = SENKOV_EBC_CHAN_REGS_base + CANKOZ_IOREGS_OFS_INPRB0,
    SENKOV_EBC_CHAN_REGS_OUTR8B     = SENKOV_EBC_CHAN_REGS_base + CANKOZ_IOREGS_OFS_OUTR8B,
    SENKOV_EBC_CHAN_REGS_INPR8B     = SENKOV_EBC_CHAN_REGS_base + CANKOZ_IOREGS_OFS_INPR8B,
    SENKOV_EBC_CHAN_REGS_last       = SENKOV_EBC_CHAN_REGS_base + CANKOZ_IOREGS_CHANCOUNT -1,

    SENKOV_EBC_CHAN_REGS_RSVD_B     = SENKOV_EBC_CHAN_REGS_base + CANKOZ_IOREGS_CHANCOUNT,
    SENKOV_EBC_CHAN_REGS_RSVD_E     = 49,
    
    SENKOV_EBC_NUMCHANS           = 50
};


#endif /* __SENKOV_EBC_DRV_I_H */
