######################################################################
#                                                                    #
#  scripts/Makefile                                                  #
#      A formal Makefile -- mainly for *clean                        #
#                                                                    #
######################################################################

SUBDIRS=
TOPDIR=		..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
