TYPES_LIST=	
TYPES_FILES=	$(foreach T, $(TYPES_LIST), $T.devtype)

GIVEN_FILES=	$(TYPES_FILES)

EXPORTSFILES=	$(TYPES_FILES)
EXPORTSDIR=	configs

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
