TYPES_LIST=	cac208 ceac124 cdac20 candac16 canadc40 \
		slio24_reg \
		cgvi8 cpks8 ckvch curvv vsdc2 caniva canipp \
		senkov_vip senkov_ebc weld02 \
		tvac320 panov_ubs \
		smc8 \
		\
		c0601 c0609 c0612 c0642 \
		g0401 g0601 g0603 g0603_simple gzi11 \
		i0633 \
		l0403 \
		r0601 \
		u0632 \
		v0308 \
		v06xx v0628 \
		dds300 dds500 \
		frolov_d16 frolov_ie4 \
		frolov_bfp frolov_bfp2 frolov_bfp16 frolov_bl700 frolov_spd \
		frolov_k4x1 frolov_k4x1_2x2x1 \
		sukh_comm24 \
		\
		adc200 adc502 adc333 adc4 c061621 f4226 \
		\
		adc200me adc812me dl200me \
		\
		adc250 adc4x250 adc1000 \
		\
		slbpm ottcam \
		kshd485 \
		triadatv_um \
		\
		vadc16 vdac20 \
		\
		pxi6363
TYPES_FILES=	$(foreach T, $(TYPES_LIST), $T.devtype)

EXPORTSFILES=	$(TYPES_FILES)
EXPORTSDIR=	configs

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
