#ifndef __LEBEDEV_SUBHARMONIC_DRV_I_H
#define __LEBEDEV_SUBHARMONIC_DRV_I_H


enum
{
    LEBEDEV_SUBHARMONIC_CHAN_SET = 0,
    LEBEDEV_SUBHARMONIC_NUMCHANS = 1
};


#endif /* __LEBEDEV_SUBHARMONIC_DRV_I_H */
