#ifndef __LEBEDEV_LINSENCTL_DRV_I_H
#define __LEBEDEV_LINSENCTL_DRV_I_H


enum
{
    LEBEDEV_LINSENCTL_CHAN_IN_STATE  = 0,
    LEBEDEV_LINSENCTL_CHAN_TIME_LEFT = 1,
    LEBEDEV_LINSENCTL_NUMCHANS = 2
};


#endif /* __LEBEDEV_LINSENCTL_DRV_I_H */
