#ifndef __LEBEDEV_RINGCAMSEL_DRV_I_H
#define __LEBEDEV_RINGCAMSEL_DRV_I_H


// w10i,r10i,r50
enum
{
    LEBEDEV_RINGCAMSEL_CHAN_CHOICE             = 0,
    LEBEDEV_RINGCAMSEL_CHAN_IS_IN              = 1,

    LEBEDEV_RINGCAMSEL_CHAN_STATE              = 10,
    LEBEDEV_RINGCAMSEL_CHAN_I_MOTOR            = 11,
    LEBEDEV_RINGCAMSEL_CHAN_TIME_LEFT          = 12,

    LEBEDEV_RINGCAMSEL_CHAN_LIMIT_SW_UP_n_base = 20,
    LEBEDEV_RINGCAMSEL_CHAN_LIMIT_SW_DN_n_base = 44,

    LEBEDEV_RINGCAMSEL_CHAN_UNUSED1 = 68,
    LEBEDEV_RINGCAMSEL_CHAN_UNUSED2 = 69,

    LEBEDEV_RINGCAMSEL_NUMCHANS = 70
};

enum
{
    LEBEDEV_RINGCAMSEL_POSITIONS_COUNT = 24,
};


#endif /* __LEBEDEV_RINGCAMSEL_DRV_I_H */
