#ifndef __LEBEDEV_LINCAMSEL_DRV_I_H
#define __LEBEDEV_LINCAMSEL_DRV_I_H

enum
{
    LEBEDEV_LINCAMSEL_CHAN_IN_n_base = 0,

#if 1
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_GUN_IN  = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 0,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_TURN_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 1,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_FAR_IN  = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 2,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_LAST_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 3,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_NONE_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 4,
#else
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_1_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 0,
    LEBEDEV_LINCAMSEL_CHAN_CONE_IN     = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 1,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_2_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 2,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_3_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 3,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_4_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 4,
    LEBEDEV_LINCAMSEL_CHAN_FARADAY_CUP_IN=LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 5,
    LEBEDEV_LINCAMSEL_CHAN_CAMERA_F_IN = LEBEDEV_LINCAMSEL_CHAN_IN_n_base + 6,
#endif

    LEBEDEV_LINCAMSEL_CHAN_TIME_LEFT = 7,

    LEBEDEV_LINCAMSEL_NUMCHANS = 8
};

#endif /* __LEBEDEV_LINCAMSEL_DRV_I_H */
