DRV_INTERFACES=	ist_cdac20_drv_i.h v1k_cdac20_drv_i.h v3h_a40d16_drv_i.h \
		mps20_ceac124_drv_i.h \
		iset_walker_drv_i.h \
		lebedev_subharmonic_drv_i.h \
		lebedev_lincamsel_drv_i.h lebedev_linsenctl_drv_i.h \
		lebedev_ringcamsel_drv_i.h lebedev_turnmag_drv_i.h \
		vepp4_gimn_drv_i.h \
		liu_key_drv_i.h liu_doorilks_drv_i.h
GIVEN_FILES=	$(DRV_INTERFACES)

EXPORTSFILES=	$(DRV_INTERFACES)
EXPORTSDIR=	include/drv_i

######################################################################
PRJDIR=		../..
include		$(PRJDIR)/PrjRules.mk
######################################################################
