#ifndef __V1K_CDAC20_DRV_I_H
#define __V1K_CDAC20_DRV_I_H


#include "ist_cdac20_drv_i.h"


// w50,r50
enum
{
    V1K_CDAC20_CHAN_WR_base      = IST_CDAC20_CHAN_WR_base,
      V1K_CDAC20_CHAN_WR_count   = IST_CDAC20_CHAN_WR_count,

    V1K_CDAC20_CHAN_ISET           = IST_CDAC20_CHAN_ISET,
    V1K_CDAC20_CHAN_ISET_RATE      = IST_CDAC20_CHAN_ISET_RATE,
    V1K_CDAC20_CHAN_SWITCH_ON      = IST_CDAC20_CHAN_SWITCH_ON,
    V1K_CDAC20_CHAN_SWITCH_OFF     = IST_CDAC20_CHAN_SWITCH_OFF,
    V1K_CDAC20_CHAN_RST_ILKS       = IST_CDAC20_CHAN_RST_ILKS,
    V1K_CDAC20_CHAN_RESET_STATE    = IST_CDAC20_CHAN_RESET_STATE,
    V1K_CDAC20_CHAN_DO_CALB_DAC    = IST_CDAC20_CHAN_DO_CALB_DAC,
    V1K_CDAC20_CHAN_AUTOCALB_ONOFF = IST_CDAC20_CHAN_AUTOCALB_ONOFF,
    V1K_CDAC20_CHAN_AUTOCALB_SECS  = IST_CDAC20_CHAN_AUTOCALB_SECS,
    V1K_CDAC20_CHAN_DIGCORR_MODE   = IST_CDAC20_CHAN_DIGCORR_MODE,
    V1K_CDAC20_CHAN_RESET_C_ILKS   = IST_CDAC20_CHAN_RESET_C_ILKS,

    
    V1K_CDAC20_CHAN_RD_base      = IST_CDAC20_CHAN_RD_base,
      V1K_CDAC20_CHAN_RD_count   = IST_CDAC20_CHAN_RD_count,

    V1K_CDAC20_CHAN_CURRENT1M      = IST_CDAC20_CHAN_RD_base + 0,
    V1K_CDAC20_CHAN_VOLTAGE2M      = IST_CDAC20_CHAN_RD_base + 1,
    V1K_CDAC20_CHAN_CURRENT2M      = IST_CDAC20_CHAN_RD_base + 2,
    V1K_CDAC20_CHAN_OUTVOLTAGE1M   = IST_CDAC20_CHAN_RD_base + 3,
    V1K_CDAC20_CHAN_OUTVOLTAGE2M   = IST_CDAC20_CHAN_RD_base + 4,
    V1K_CDAC20_CHAN_ADC_DAC        = IST_CDAC20_CHAN_ADC_DAC,
    V1K_CDAC20_CHAN_ADC_0V         = IST_CDAC20_CHAN_ADC_0V,
    V1K_CDAC20_CHAN_ADC_P10V       = IST_CDAC20_CHAN_ADC_P10V,

    V1K_CDAC20_CHAN_ISET_CUR       = IST_CDAC20_CHAN_ISET_CUR,
    
    V1K_CDAC20_CHAN_DIGCORR_FACTOR = IST_CDAC20_CHAN_DIGCORR_FACTOR,

    V1K_CDAC20_CHAN_OPR            = IST_CDAC20_CHAN_OPR,
    
    V1K_CDAC20_CHAN_ILK_base     =   IST_CDAC20_CHAN_ILK_base,
      V1K_CDAC20_CHAN_ILK_count  =   4,
    V1K_CDAC20_CHAN_ILK_OVERHEAT   = V1K_CDAC20_CHAN_ILK_base + 0,
    V1K_CDAC20_CHAN_ILK_EMERGSHT   = V1K_CDAC20_CHAN_ILK_base + 1,
    V1K_CDAC20_CHAN_ILK_CURRPROT   = V1K_CDAC20_CHAN_ILK_base + 2,
    V1K_CDAC20_CHAN_ILK_LOADOVRH   = V1K_CDAC20_CHAN_ILK_base + 3,

    V1K_CDAC20_CHAN_IS_ON          = IST_CDAC20_CHAN_IS_ON,

    V1K_CDAC20_CHAN_C_ILK_base   =   IST_CDAC20_CHAN_C_ILK_base,
      V1K_CDAC20_CHAN_C_ILK_count=   IST_CDAC20_CHAN_C_ILK_count,
    V1K_CDAC20_CHAN_C_ILK_OVERHEAT = V1K_CDAC20_CHAN_C_ILK_base + 0,
    V1K_CDAC20_CHAN_C_ILK_EMERGSHT = V1K_CDAC20_CHAN_C_ILK_base + 1,
    V1K_CDAC20_CHAN_C_ILK_CURRPROT = V1K_CDAC20_CHAN_C_ILK_base + 2,
    V1K_CDAC20_CHAN_C_ILK_LOADOVRH = V1K_CDAC20_CHAN_C_ILK_base + 3,

    V1K_CDAC20_CHAN_VDEV_CONDITION = IST_CDAC20_CHAN_VDEV_CONDITION,
    V1K_CDAC20_CHAN_VDEV_STATE     = IST_CDAC20_CHAN_VDEV_STATE,

    V1K_CDAC20_NUMCHANS          =   IST_CDAC20_NUMCHANS,
};


#endif /* __V1K_CDAC20_DRV_I_H */
